### ISSUE TITLE
Example provider friends list for rolodex

### ISSUE THREAD

**Issue by robin-raymond** [hookflash/obsolete.op-identity-provider-server-php#33]
I've been thinking that the example provider should make an "auto friends list" for the rolodex. This list should include all friends under the same app ID.

This would make a good way to easily test the application by us and others but not create a massive impossible list over time since the list is scoped just to those whom share the same app ID.

What do you think?

cc: @adriano-maljkovic

**Comment by cadorn** [comment]
I like it. How would the implementation work?

**Comment by robin-raymond** [comment]
Since we control ID provider sample, ID provider DB needs to organize contacts by app ID (obviously), and rolodex service needs to use API exposed by ID provider to fetch contacts.

Very vague in details, I know but we should come up with an API though I suspect (and use that as a basis for making a generic rolodex API in the future between us [hosted service] and 3rd party ID providers [customer]).

**Comment by adriano-maljkovic** [comment]
This can easily be done after https://github.com/openpeer/op-identity-provider-server-php/issues/34 is fixed. I can perform the implementation if you'd like...

**Comment by adriano-maljkovic** [comment]
@robin-raymond where do you want me to define messages between system entities? In annex-rolodex maybe?

**Comment by adriano-maljkovic** [comment]
@cadorn @robin-raymond https://github.com/openpeer/hcs-system/blob/master/architecture/servers/HCS%20protocol%20-%20Identity%20Provider,%20Federated%20Contacts%20Per%20Application.md

The idea is to make minimal changes in the existing pattern of messages that are used in ...-contacts-get scenarios, such as facebook.

So, everything stays the same as fb contacts, there is only one additional message from rolodex to id provider in order to provide the list of contacts.

Please let me know if you agree that an Identity Provider trusts whomever has a correct hosting secret proof!

_NOTE: An account is being re-attached to an appid upon every login, and because of that rolodex should refetch contacts on upon every `rolodex-contacts-get` request_

**Comment by adriano-maljkovic** [comment]
almost code-complete

**Comment by cadorn** [comment]
See: https://github.com/openpeer/rolodex/issues/29
