### ISSUE TITLE
Facebook login, logout, facebook login not working

### ISSUE THREAD

**Issue by cadorn** [hookflash/obsolete.op-identity-provider-server-php#38]
After logging in again UI is stuck on `Opening login page ...`.

Example: http://legacy.instances.system.hookflash.com/logs#identity-cpp-1382052405443-net.cadorn.hookflash.app1-67RlEb3zNtxxx-1384644391-e218309be1xxx
From line `unable to associate identity as already shutdown` down is relogin.

**Comment by adriano-maljkovic** [comment]
The scenario isn't completely clear here. What I tried is:
1. Login using fb identity for the first time
2. Kill app
3. Deploy app
4. Login using the same fb identity
And it works. It would be better if you provide actual scenario through steps, since I'm not sure if I understand it from what's put here in the ticket.

**Comment by robin-raymond** [comment]
@cadorn I'm not clear in the scenario either

I see this in the log:
core::Account [11] shutdown called

That only happens if the GUI wants the application to shutdown. When that happens, ever identity loaded and associated to this core account will shutdown as well.

From what I see in the logs, the GUI seems to have been shutdown, then after the shutdown was complete, another identity was added to the already shutdown core account.

Perhaps the issue is that the GUI is not forgetting the "core::Account" object after the application is logout and creating a new one upon a fresh login to a new account?

cc: @SergioOpenPeer this issue is related to GUI perhaps

**Comment by adriano-maljkovic** [comment]
@robin-raymond should I re-assign?
And, if so, to whom?

Also, might this be an attempt to associate fb account with another fb account? (Which isn't supported yet)

**Comment by cadorn** [comment]
By `Logout` I mean _Settings Tab_ -> _Logout Button_. By it works I mean goes through login sequence and contacts show. I never killed/exited the app.

**Comment by robin-raymond** [comment]
@cadorn think this is a GUI problem by not "forgetting" the already shutdown core::Account
